apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a0kb9mefg-python
  janus-idp.io/tekton: a0kb9mefg-python
  backstage.io/kubernetes-id: a0kb9mefg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a0kb9mefg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
